KKKKKKKKK    KKKKKKK  iiii                                                        hhhhhhh                               kkkkkkkk                                                     IIIIIIIIII                                                                             
K:::::::K    K:::::K i::::i                                                       h:::::h                               k::::::k                                                     I::::::::I                                                                             
K:::::::K    K:::::K  iiii                                                        h:::::h                               k::::::k                                                     I::::::::I                                                                             
K:::::::K   K::::::K                                                              h:::::h                               k::::::k                                                     II::::::II                                                                             
KK::::::K  K:::::KKKiiiiiiinnnn  nnnnnnnn       ggggggggg   ggggg                  h::::h hhhhh         aaaaaaaaaaaaa    k:::::k    kkkkkkk eeeeeeeeeeee    rrrrr   rrrrrrrrr          I::::I     mmmmmmm    mmmmmmm   rrrrr   rrrrrrrrr   aaaaaaaaaaaaa  nnnn  nnnnnnnn    
  K:::::K K:::::K   i:::::in:::nn::::::::nn    g:::::::::ggg::::g                  h::::hh:::::hhh      a::::::::::::a   k:::::k   k:::::kee::::::::::::ee  r::::rrr:::::::::r         I::::I   mm:::::::m  m:::::::mm r::::rrr:::::::::r  a::::::::::::a n:::nn::::::::nn  
  K::::::K:::::K     i::::in::::::::::::::nn  g:::::::::::::::::g                  h::::::::::::::hh    aaaaaaaaa:::::a  k:::::k  k:::::ke::::::eeeee:::::eer:::::::::::::::::r        I::::I  m::::::::::mm::::::::::mr:::::::::::::::::r aaaaaaaaa:::::an::::::::::::::nn 
  K:::::::::::K      i::::inn:::::::::::::::ng::::::ggggg::::::gg ---------------  h:::::::hhh::::::h            a::::a  k:::::k k:::::ke::::::e     e:::::err::::::rrrrr::::::r       I::::I  m::::::::::::::::::::::mrr::::::rrrrr::::::r         a::::ann:::::::::::::::n
  K:::::::::::K      i::::i  n:::::nnnn:::::ng:::::g     g:::::g  -:::::::::::::-  h::::::h   h::::::h    aaaaaaa:::::a  k::::::k:::::k e:::::::eeeee::::::e r:::::r     r:::::r       I::::I  m:::::mmm::::::mmm:::::m r:::::r     r:::::r  aaaaaaa:::::a  n:::::nnnn:::::n
  K::::::K:::::K     i::::i  n::::n    n::::ng:::::g     g:::::g  ---------------  h:::::h     h:::::h  aa::::::::::::a  k:::::::::::k  e:::::::::::::::::e  r:::::r     rrrrrrr       I::::I  m::::m   m::::m   m::::m r:::::r     rrrrrrraa::::::::::::a  n::::n    n::::n
  K:::::K K:::::K    i::::i  n::::n    n::::ng:::::g     g:::::g                   h:::::h     h:::::h a::::aaaa::::::a  k:::::::::::k  e::::::eeeeeeeeeee   r:::::r                   I::::I  m::::m   m::::m   m::::m r:::::r           a::::aaaa::::::a  n::::n    n::::n
KK::::::K  K:::::KKK i::::i  n::::n    n::::ng::::::g    g:::::g                   h:::::h     h:::::ha::::a    a:::::a  k::::::k:::::k e:::::::e            r:::::r                   I::::I  m::::m   m::::m   m::::m r:::::r          a::::a    a:::::a  n::::n    n::::n
K:::::::K   K::::::Ki::::::i n::::n    n::::ng:::::::ggggg:::::g                   h:::::h     h:::::ha::::a    a:::::a k::::::k k:::::ke::::::::e           r:::::r                 II::::::IIm::::m   m::::m   m::::m r:::::r          a::::a    a:::::a  n::::n    n::::n
K:::::::K    K:::::Ki::::::i n::::n    n::::n g::::::::::::::::g                   h:::::h     h:::::ha:::::aaaa::::::a k::::::k  k:::::ke::::::::eeeeeeee   r:::::r                 I::::::::Im::::m   m::::m   m::::m r:::::r          a:::::aaaa::::::a  n::::n    n::::n
K:::::::K    K:::::Ki::::::i n::::n    n::::n  gg::::::::::::::g                   h:::::h     h:::::h a::::::::::aa:::ak::::::k   k:::::kee:::::::::::::e   r:::::r                 I::::::::Im::::m   m::::m   m::::m r:::::r           a::::::::::aa:::a n::::n    n::::n
KKKKKKKKK    KKKKKKKiiiiiiii nnnnnn    nnnnnn    gggggggg::::::g                   hhhhhhh     hhhhhhh  aaaaaaaaaa  aaaakkkkkkkk    kkkkkkk eeeeeeeeeeeeee   rrrrrrr                 IIIIIIIIIImmmmmm   mmmmmm   mmmmmm rrrrrrr            aaaaaaaaaa  aaaa nnnnnn    nnnnnn
                                                         g:::::g                                                                                                                                                                                                            
                                             gggggg      g:::::g                                                                                                                                                                                                            
                                             g:::::gg   gg:::::g                                                                                                                                                                                                            
                                              g::::::ggg:::::::g                                                                                                                                                                                                            
                                               gg:::::::::::::g                                                                                                                                                                                                             
                                                 ggg::::::ggg                                                                                                                                                                                                               
                                                    gggggg